-- create tables
create table d601_documento (
    id                             number generated by default on null as identity 
                                   constraint d601_documento_id_pk primary key,
    codice                         varchar2(20 char)
                                   constraint d601_documento_codice_unq unique not null,
    descrizione                    varchar2(50 char) not null,
    the_file                       blob,
    file_filename                  varchar2(512 char),
    file_mimetype                  varchar2(512 char),
    file_charset                   varchar2(512 char),
    file_lastupd                   date,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

create table d601_dipartimento (
    id                             number generated by default on null as identity 
                                   constraint d601_dipartimento_id_pk primary key,
    dipartimento                   varchar2(20 char)
                                   constraint d601_dipartimen_dipartimen_unq unique not null,
    dipartimento_des               varchar2(50 char) not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

create table d601_gruppo (
    id                             number generated by default on null as identity 
                                   constraint d601_gruppo_id_pk primary key,
    dipartimento_id                number
                                   constraint d601_gruppo_dipartimento_id_fk
                                   references d601_dipartimento on delete cascade not null,
    gruppo                         varchar2(20 char)
                                   constraint d601_gruppo_gruppo_unq unique not null,
    gruppo_des                     varchar2(4000 char) not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index d601_gruppo_i1 on d601_gruppo (dipartimento_id);

create table d601_utente (
    id                             number generated by default on null as identity 
                                   constraint d601_utente_id_pk primary key,
    utente                         varchar2(20 char)
                                   constraint d601_utente_utente_unq unique not null,
    nome                           varchar2(50 char) not null,
    email                          varchar2(50 char) not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

create table d601_utente_gruppo (
    id                             number generated by default on null as identity 
                                   constraint d601_utente_gruppo_id_pk primary key,
    utente_id                      number
                                   constraint d601_utente_gruppo_utente_i_fk
                                   references d601_utente on delete cascade not null,
    gruppo_id                      number
                                   constraint d601_utente_gruppo_gruppo_i_fk
                                   references d601_gruppo on delete cascade not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index d601_utente_gruppo_i1 on d601_utente_gruppo (gruppo_id);
create index d601_utente_gruppo_i142 on d601_utente_gruppo (utente_id);

create table d601_gruppo_approvatore (
    id                             number generated by default on null as identity 
                                   constraint d601_gruppo_approv_id_pk primary key,
    documento_id                   number
                                   constraint d601_gruppo_app_documento_i_fk
                                   references d601_documento on delete cascade not null,
    gruppo_id                      number
                                   constraint d601_gruppo_approv_gruppo_i_fk
                                   references d601_gruppo on delete cascade not null,
    ordine                         number not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index d601_gruppo_approv_i1 on d601_gruppo_approvatore (documento_id);
create index d601_gruppo_approv_i192 on d601_gruppo_approvatore (gruppo_id);


-- triggers
create or replace trigger d601_documento_biu
    before insert or update 
    on d601_documento
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d601_documento_biu;
/

create or replace trigger d601_dipartimento_biu
    before insert or update 
    on d601_dipartimento
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d601_dipartimento_biu;
/

create or replace trigger d601_gruppo_biu
    before insert or update 
    on d601_gruppo
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d601_gruppo_biu;
/

create or replace trigger d601_utente_biu
    before insert or update 
    on d601_utente
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d601_utente_biu;
/

create or replace trigger d601_utente_gruppo_biu
    before insert or update 
    on d601_utente_gruppo
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d601_utente_gruppo_biu;
/

create or replace trigger d601_gruppo_approvatore_biu
    before insert or update 
    on d601_gruppo_approvatore
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d601_gruppo_approvatore_biu;
/

-- load data
 
-- Generated by Quick SQL Martedì Novembre 28, 2023  10:15:56
 
/*
documento
  codice vc20 /nn /unique
  descrizione vc50 /nn
  file file

dipartimento
  dipartimento vc20 /nn /unique
  dipartimento_des vc50 /nn

gruppo
  gruppo vc20 /nn /unique
  gruppo_des /nn
  dipartimento_id /nn

utente
  utente vc20 /nn /unique
  nome vc50 /nn
  email vc50 /nn

utente_gruppo
  utente_id /nn
  gruppo_id /nn

gruppo_approvatore
  documento_id /nn
  gruppo_id /nn
  ordine num /nn  
# settings = { prefix: "D601", semantics: "CHAR", auditCols: true, language: "EN", APEX: true }
*/
